import { Providers } from '@/redux/provider';
import './globals.css';
import type { Metadata } from 'next';
import { Roboto, Roboto_Mono } from 'next/font/google';
import { Toaster } from 'react-hot-toast';

const roboto = Roboto({
    weight: ['100', '300', '400', '500', '700', '900'],
    variable: '--roboto',
    subsets: ['latin'],
    style: 'normal',
});

const roboto_mono = Roboto_Mono({
    weight: ['100', '300', '400', '500', '700'],
    variable: '--roboto-mono',
    subsets: ['latin'],
    style: 'normal',
});

export const metadata: Metadata = {
    title: 'Postman',
    description: 'Generated by create next app',
};

const AppLayout = ({ children }: { children: React.ReactNode }) => {
    return (
        <html lang="en">
            <body
                className={`${roboto.variable} ${roboto_mono.variable}`}
                suppressHydrationWarning={true}>
                <Providers>
                    <Toaster position="top-center" reverseOrder={false} />
                    {children}
                </Providers>
            </body>
        </html>
    );
};

export default AppLayout;
